name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Start SonarScanner
        run: |
          dotnet sonarscanner begin /k:"TwnaShop" /d:sonar.host.url="http://192.168.1.13:9000" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Build Project
        run: dotnet build

      - name: End SonarScanner
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
